"""动画层包：导入各模块以填充注册表（策略模式 + ANIM_REGISTRY）。"""

from .background import (
    BgAssets,
    BgState,
    BreathZoomBG,
    GradientWaveBG,
    MidnightBG,
    StaticBlurBG,
    WaveBlurBG,
)
from .base import (
    ANIM_REGISTRY,
    KIND_BACKGROUND,
    KIND_COVER,
    KIND_FILTER,
    KIND_LYRICS,
    KINDS,
    BaseLayer,
    ParamSpec,
    animation_groups,
    clamp,
    layer_class,
)
from .cover import (
    BreathCover,
    CelestialCover,
    CoverAssets,
    CoverState,
    DiscRotate,
    FloatCover,
    Rock3DCover,
    StaticCover,
)
from .lyrics import (
    ArcLyrics,
    FadeLyrics,
    Flip3DLyrics,
    LyricItem,
    LyricsAssets,
    LyricsState,
    RevealLyrics,
    ScrollListLyrics,
    SlideLyrics,
)
from .filters import FilterAssets, FilterState, LightLeakFilter, BokehFilter, NoFilter

__all__ = [
    "ANIM_REGISTRY",
    "KINDS",
    "KIND_BACKGROUND",
    "KIND_COVER",
    "KIND_FILTER",
    "FilterAssets",
    "FilterState",
    "LightLeakFilter",
    "BokehFilter",
    "NoFilter",
    "KIND_LYRICS",
    "ArcLyrics",
    "BaseLayer",
    "BgAssets",
    "BgState",
    "BreathCover",
    "BreathZoomBG",
    "CelestialCover",
    "CoverAssets",
    "CoverState",
    "DiscRotate",
    "FadeLyrics",
    "Flip3DLyrics",
    "FloatCover",
    "GradientWaveBG",
    "LyricItem",
    "LyricsAssets",
    "LyricsState",
    "MidnightBG",
    "ParamSpec",
    "RevealLyrics",
    "Rock3DCover",
    "ScrollListLyrics",
    "SlideLyrics",
    "StaticBlurBG",
    "StaticCover",
    "WaveBlurBG",
    "animation_groups",
    "clamp",
    "layer_class",
]
